language: node_js

node_js: stable

cache: yarn

before_install: yarn global add greenkeeper-lockfile

before_script: greenkeeper-lockfile-update

script:
  - yarn lint
  - yarn build
  - 'if [[ $TRAVIS_BRANCH = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then yarn sync:static; fi'

after_script: greenkeeper-lockfile-upload
