name: Node CI

on:
  - push
  - pull_request

jobs:
  default:
    strategy:
      matrix:
        node:
          - 18
        os:
          - macOS-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build, Lint
        run: |
          yarn lint
          yarn build
        env:
          EFF_NO_LINK_RULES: 'true'
          PARSER_NO_WATCH: 'true'
